### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by 827346462** [PeterH0323/Smart_Construction#62]
ghts ./weights/helmet_head_person_m.pt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.4, device='', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='000017.jpg', update=False, view_img=False, weights=['./weights/helmet_head_person_m.pt'])
Using CUDA device0 _CudaDeviceProperties(name='NVIDIA GeForce RTX 3090', total_memory=24267MB)

Fusing layers... Traceback (most recent call last):
  File "detect.py", line 161, in <module>
    detect()
  File "detect.py", line 23, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/sevnce/Smart_Construction/Smart_Construction-master/models/experimental.py", line 133, in attempt_load
    model.append(torch.load(w, map_location=map_location)['model'].float().fuse().eval())  # load FP32 model
  File "/home/sevnce/Smart_Construction/Smart_Construction-master/models/yolo.py", line 150, in fuse
    m.conv = torch_utils.fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/sevnce/Smart_Construction/Smart_Construction-master/utils/torch_utils.py", line 113, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.size()))
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

我在ubuntu 18.04 cuda11.2 rtx3090 环境 虚拟环境是requirment.txt.
直接运行 python detect.py --source 000017.jpg --weights ./weights/helmet_head_person_m.pt
出现cuda 错误。
请问这个cuda版本和权重不适配的问题吗

**Comment by piwawa** [comment]
我在ubuntu直接 python visual_interface.py 都运行不了
